2019-12-07 16:47:00,967 ERROR: Exception on /post/5 [POST] [in /home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/honery/Documents/cursach/app/routes.py", line 179, in post
    return redirect(url_for('post'), post_id)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'post'. Did you forget to specify values ['post_id']?
2019-12-07 16:47:37,763 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
2019-12-07 16:47:41,538 ERROR: Exception on /post/5 [POST] [in /home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/honery/Documents/cursach/app/routes.py", line 179, in post
    return redirect(url_for('post', post_id))
TypeError: url_for() takes 1 positional argument but 2 were given
2019-12-07 16:47:58,265 ERROR: Exception on /post/5 [POST] [in /home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/honery/Documents/cursach/app/routes.py", line 179, in post
    return redirect(url_for('post', post_id))
TypeError: url_for() takes 1 positional argument but 2 were given
2019-12-07 16:48:20,163 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
2019-12-07 16:53:29,816 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
